sonar.projectKey=insaze_ai_interview
sonar.organization=insaze
sonar.python.coverage.reportPaths=coverage-reports/backend.xml
sonar.javascript.lcov.reportPaths=coverage-reports/lcov.info
sonar.exclusions=**/tests/**,**/jenkins/**,**/tg_bot/**
