sonar.projectKey=insaze_ai_interview
sonar.organization=insaze
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.javascript.lcov.reportPaths=frontend/interview-app/coverage/lcov.info
sonar.exclusions=**/tests/**,**/jenkins/**,**/tg_bot/**
