name: CI Build, Test & Deploy

on:
  push:
    branches: [ master ]

jobs:
  frontend-test:
    name: Run Frontend Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        working-directory: frontend/interview-app
        with:
          node-version: 20
          cache: 'npm'
      
      - name: Install dependencies
        working-directory: frontend/interview-app
        run: npm ci
      
      - name: Run tests
        working-directory: frontend/interview-app
        run: npm test -- --watchAll=false --coverage

  frontend-build-and-deploy:
    name: Build and Deploy
    needs: frontend-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        working-directory: frontend/interview-app
        with:
          node-version: 20
          cache: 'npm'
      
      - name: Install dependencies
        working-directory: frontend/interview-app
        run: npm ci
      
      - name: Build project
        working-directory: frontend/interview-app
        run: npm run build
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        working-directory: frontend/interview-app
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build