name: Deploy to Kubernetes

on:
  push:
    branches: [ main, lab4 ]
  pull_request:
    branches: [ main, lab4 ]

env:
  CLUSTER_NAME: "kubernetes"
  NAMESPACE: "default"
  HELM_CHART: "./helm"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: 'v3.13.2'
        
    - name: Install client-keystone-auth
      run: |
        curl -sSL https://hub.mcs.mail.ru/repository/client-keystone-auth/latest/linux/client-install.sh  | bash
        source ~/.bashrc

    - name: Configure Kubernetes
      uses: azure/k8s-set-context@v3
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBE_CONFIG }}

    - name: Test kubectl access
      run: |
        kubectl version --short
    
    - name: Install/Upgrade Helm Chart
      run: |
        helm upgrade --install \
          --namespace ${{ env.NAMESPACE }} \
          --atomic \
          --set-string "global.insecureSkipVerify=true" \
          --set frontend.apiBaseURL="${{ secrets.API_BASE_URL }}" \
          --insecure-skip-tls-verify \
          ai-interview \
          ${{ env.HELM_CHART }} \
          --values ${{ env.HELM_CHART }}/values.yaml \
#         --wait \
