name: Deploy

on:
  push:
    branches: [ main, lab4 ]
  pull_request:
    branches: [ main, lab4 ]

env:
  CLUSTER_NAME: "kubernetes"
  NAMESPACE: "default"
  HELM_CHART: "./helm"
  IMAGE_PULL_SECRETS_KEY: "regcred"

jobs:
  build-and-push:
    name: "Build and push to docker registry"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_LOGIN }} -p ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push Backend image
        run: |
          docker build -t ${{ secrets.DOCKER_LOGIN }}/backend:latest backend
          docker push ${{ secrets.DOCKER_LOGIN }}/backend:latest

      - name: Build and push Frontend image
        run: |
          docker build -t ${{ secrets.DOCKER_LOGIN }}/frontend:latest frontend/interview-app
          docker push ${{ secrets.DOCKER_LOGIN }}/frontend:latest

      - name: Build and push ML Service image
        run: |
          docker build -t ${{ secrets.DOCKER_LOGIN }}/ml_service:latest ml_service
          docker push ${{ secrets.DOCKER_LOGIN }}/ml_service:latest

      - name: Build and push TG Bot image
        run: |
          docker build -t ${{ secrets.DOCKER_LOGIN }}/tg_bot:latest tg_bot
          docker push ${{ secrets.DOCKER_LOGIN }}/tg_bot:latest
  deploy:
    name: "Deploy to k8s"
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: 'v3.13.2'
        
    - name: Install client-keystone-auth
      run: |
        curl -sSL https://hub.mcs.mail.ru/repository/client-keystone-auth/latest/linux/client-install.sh  | bash

    - name: Configure Kubernetes
      uses: azure/k8s-set-context@v3
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBE_CONFIG }}

    - name: Test kubectl access
      run: |
        source ~/vk-cloud-solutions/path.bash.inc
        kubectl version

    - name: Setup k8s secrets
      run: |
        source ~/vk-cloud-solutions/path.bash.inc
        
        kubectl delete secret tg-token -n ${{ env.NAMESPACE }} --ignore-not-found
        kubectl create secret generic tg-token --from-literal=TG_TOKEN=${{ secrets.TG_TOKEN }} -n ${{ env.NAMESPACE }}
        
        kubectl delete secret gigachat2 -n ${{ env.NAMESPACE }} --ignore-not-found
        kubectl create secret generic gigachat2 --from-literal=GIGACHAT_API_KEY=${{ secrets.GIGACHAT_API_KEY }} -n ${{ env.NAMESPACE }}
        
        kubectl delete secret ${{ env.IMAGE_PULL_SECRETS_KEY }} -n ${{ env.NAMESPACE }} --ignore-not-found
        kubectl create secret docker-registry ${{ env.IMAGE_PULL_SECRETS_KEY }} \
          --docker-server=https://index.docker.io/v1/  \
          --docker-username=${{ secrets.DOCKER_LOGIN }} \
          --docker-password=${{ secrets.DOCKER_ACCESS_TOKEN }} \
          --docker-email=${{ secrets.DOCKER_EMAIL }} \
          -n ${{ env.NAMESPACE }}

    - name: Install/Upgrade Helm Chart
      run: |
        source ~/vk-cloud-solutions/path.bash.inc
        
        helm dependency update ${{ env.HELM_CHART }}
        helm upgrade --install \
          --atomic \
          --namespace ${{ env.NAMESPACE }} \
          --insecure-skip-tls-verify \
          --set frontend.apiBaseURL="${{ secrets.API_BASE_URL }}" \
          ai-interview \
          ${{ env.HELM_CHART }} \
          --values ${{ env.HELM_CHART }}/values.yaml \
